blank_issues_enabled: false
contact_links:
  - name: "â“ Question / Support"
    url: "https://github.com/tajemniktv/TajsMod/issues/new?template=question.yml"
    about: "Ask here if you need help or have a general question not covered by bug or feature forms."
